/**
 * @Generated by sagacity-quickvo 5.0
 */
package cn.fanzy.atfield.infra.entity;

import cn.fanzy.atfield.sqltoy.entity.BaseEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @project spider-starter
 * @author fanzaiyang
 * @version 1.0.0
 */
@Schema(description = "系统操作记录表")
@EqualsAndHashCode(callSuper = true)
@Data
@Accessors(chain = true)
@Entity(tableName = "sys_operate_info", comment = "系统操作记录表", pk_constraint = "PRIMARY")
public class SysOperateInfoDO extends BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 4985429426864099384L;
    /*---begin-auto-generate-don't-update-this-area--*/

    @Schema(description = "主键", nullable = false)
    @Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
    @Column(name = "id", comment = "主键", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = false)
    private String id;

    @Schema(description = "模块名称", nullable = true)
    @Column(name = "title", comment = "模块名称", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String title;

    @Schema(description = "二级名称", nullable = true)
    @Column(name = "sub_title", comment = "二级名称", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String subTitle;

    @Schema(description = "操作类型", nullable = true)
    @Column(name = "operate_type", comment = "操作类型", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String operateType;

    @Schema(description = "用户ID", nullable = true)
    @Column(name = "user_id", comment = "用户ID", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String userId;

    @Schema(description = "操作设备", nullable = true)
    @Column(name = "operate_device", comment = "操作设备", length = 512L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String operateDevice;

    @Schema(description = "操作IP", nullable = true)
    @Column(name = "operate_ip", comment = "操作IP", length = 20L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String operateIp;

    @Schema(description = "请求类型;GET/POST", nullable = true)
    @Column(name = "request_type", comment = "请求类型;GET/POST", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String requestType;

    @Schema(description = "请求时间", nullable = true)
    @Column(name = "request_time", comment = "请求时间", length = 19L, type = java.sql.Types.DATE, nativeType = "DATETIME", nullable = true)
    private LocalDateTime requestTime;

    @Schema(description = "请求方法", nullable = true)
    @Column(name = "request_method", comment = "请求方法", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String requestMethod;

    @Schema(description = "请求URL", nullable = true)
    @Column(name = "request_url", comment = "请求URL", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String requestUrl;

    @Schema(description = "请求参数", nullable = true)
    @Column(name = "request_data", comment = "请求参数", length = 65535L, type = java.sql.Types.VARCHAR, nativeType = "TEXT", nullable = true)
    private String requestData;

    @Schema(description = "响应时间", nullable = true)
    @Column(name = "response_time", comment = "响应时间", length = 19L, type = java.sql.Types.DATE, nativeType = "DATETIME", nullable = true)
    private LocalDateTime responseTime;

    @Schema(description = "响应内容", nullable = true)
    @Column(name = "response_data", comment = "响应内容", length = 65535L, type = java.sql.Types.VARCHAR, nativeType = "TEXT", nullable = true)
    private String responseData;

    @Schema(description = "响应消息", nullable = true)
    @Column(name = "response_message", comment = "响应消息", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String responseMessage;

    @Schema(description = "响应结果;1-成功，0-失败", nullable = true)
    @Column(name = "response_result", comment = "响应结果;1-成功，0-失败", length = 5L, type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer responseResult;

    @Schema(description = "花费时间;毫秒", nullable = true)
    @Column(name = "spend_time", comment = "花费时间;毫秒", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
    private Integer spendTime;

    @Schema(description = "备注说明", nullable = true)
    @Column(name = "remarks", comment = "备注说明", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String remarks;

    @Schema(description = "状态;1-有效，0-无效", nullable = true)
    @Column(name = "status", comment = "状态;1-有效，0-无效", length = 5L, defaultValue = "1", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer status;

    /**
     * default constructor
     */
    public SysOperateInfoDO() {
    }

    /**
     * pk constructor
     */
    public SysOperateInfoDO(String id) {
        this.id = id;
    }
    /*---end-auto-generate-don't-update-this-area--*/
}
