/**
 * @Generated by sagacity-quickvo 5.0
 */
package cn.fanzy.atfield.infra.entity;

import cn.fanzy.atfield.sqltoy.entity.BaseEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serial;
import java.io.Serializable;

/**
 * @author fanzaiyang
 * @version 1.0.0
 * @project spider-starter
 */
@Schema(description = "中国行政地区表")
@EqualsAndHashCode(callSuper = true)
@Data
@Accessors(chain = true)
@Entity(tableName = "sys_region", comment = "中国行政地区表", pk_constraint = "PRIMARY")
public class SysRegionDO extends BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 221856373922233073L;
    /*---begin-auto-generate-don't-update-this-area--*/

    @Schema(description = "", nullable = false)
    @Id(strategy = "identity")
    @Column(name = "id", comment = "", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = false, autoIncrement = true)
    private Integer id;

    @Schema(description = "区域编码", nullable = false)
    @Column(name = "adcode", comment = "区域编码", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = false)
    private Integer adcode;

    @Schema(description = "城市代码", nullable = true)
    @Column(name = "city_code", comment = "城市代码", length = 10L, defaultValue = "0", type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
    private Integer cityCode;

    @Schema(description = "行政区划名字", nullable = false)
    @Column(name = "name", comment = "行政区划名字", length = 90L, defaultValue = "0", type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = false)
    private String name;

    @Schema(description = "区域中心点", nullable = true)
    @Column(name = "center", comment = "区域中心点", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String center;

    @Schema(description = "组合名", nullable = true)
    @Column(name = "merger_name", comment = "组合名", length = 50L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String mergerName;

    @Schema(description = "拼音", nullable = true)
    @Column(name = "pinyin", comment = "拼音", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String pinyin;

    @Schema(description = "上级ID", nullable = true)
    @Column(name = "parent_id", comment = "上级ID", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
    private Integer parentId;

    @Schema(description = "是否叶子结点;1-是，0-否", nullable = true)
    @Column(name = "is_leaf", comment = "是否叶子结点;1-是，0-否", length = 5L, type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer isLeaf;

    @Schema(description = "节点类型;country:国家 province:省份（直辖市会在province显示） city:市（直辖市会在province显示） district:区县 street:街道", nullable = true)
    @Column(name = "node_type", comment = "节点类型;country:国家 province:省份（直辖市会在province显示） city:市（直辖市会在province显示） district:区县 street:街道", length = 12L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String nodeType;

    @Schema(description = "节点级别", nullable = true)
    @Column(name = "node_level", comment = "节点级别", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
    private Integer nodeLevel;

    @Schema(description = "节点路由", nullable = true)
    @Column(name = "node_route", comment = "节点路由", length = 65535L, type = java.sql.Types.VARCHAR, nativeType = "TEXT", nullable = true)
    private String nodeRoute;

    @Schema(description = "备注说明", nullable = true)
    @Column(name = "remarks", comment = "备注说明", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String remarks;

    @Schema(description = "状态;1-有效，0-无效", nullable = true)
    @Column(name = "status", comment = "状态;1-有效，0-无效", length = 5L, defaultValue = "1", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer status;

    /**
     * default constructor
     */
    public SysRegionDO() {
    }

    /**
     * pk constructor
     */
    public SysRegionDO(Integer id) {
        this.id = id;
    }
    /*---end-auto-generate-don't-update-this-area--*/
}
