/**
 * @Generated by sagacity-quickvo 5.0
 */
package cn.fanzy.atfield.infra.entity;

import cn.fanzy.atfield.sqltoy.entity.BaseEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @project spider-starter
 * @author fanzaiyang
 * @version 1.0.0
 */
@Schema(description = "系统登录历史记录表")
@EqualsAndHashCode(callSuper = true)
@Data
@Accessors(chain = true)
@Entity(tableName = "ums_admin_login_history", comment = "系统登录历史记录表", pk_constraint = "PRIMARY")
public class UmsAdminLoginHistoryDO extends BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1944325917216394938L;
    /*---begin-auto-generate-don't-update-this-area--*/

    @Schema(description = "主键", nullable = false)
    @Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
    @Column(name = "id", comment = "主键", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = false)
    private String id;

    @Schema(description = "客户端ID", nullable = true)
    @Column(name = "client_id", comment = "客户端ID", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String clientId;

    @Schema(description = "登录时间", nullable = true)
    @Column(name = "login_time", comment = "登录时间", length = 19L, type = java.sql.Types.DATE, nativeType = "DATETIME", nullable = true)
    private LocalDateTime loginTime;

    @Schema(description = "登录方式;PASSWORD/PHONE/WECHAT...", nullable = true)
    @Column(name = "login_type", comment = "登录方式;PASSWORD/PHONE/WECHAT...", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String loginType;

    @Schema(description = "用户ID", nullable = true)
    @Column(name = "login_id", comment = "用户ID", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String loginId;

    @Schema(description = "登录名", nullable = true)
    @Column(name = "login_name", comment = "登录名", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String loginName;

    @Schema(description = "登录参数", nullable = true)
    @Column(name = "login_param", comment = "登录参数", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String loginParam;

    @Schema(description = "登录IP", nullable = true)
    @Column(name = "login_ip", comment = "登录IP", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String loginIp;

    @Schema(description = "登录结果;1-成功，0-失败", nullable = true)
    @Column(name = "login_result", comment = "登录结果;1-成功，0-失败", length = 5L, type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer loginResult;

    @Schema(description = "登录结果描述", nullable = true)
    @Column(name = "login_result_remark", comment = "登录结果描述", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String loginResultRemark;

    @Schema(description = "登录结果时间", nullable = true)
    @Column(name = "login_result_time", comment = "登录结果时间", length = 19L, type = java.sql.Types.DATE, nativeType = "DATETIME", nullable = true)
    private LocalDateTime loginResultTime;

    @Schema(description = "是否为移动平台", nullable = true)
    @Column(name = "mobile", comment = "是否为移动平台", length = 5L, type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer mobile;

    @Schema(description = "浏览器类型", nullable = true)
    @Column(name = "browser", comment = "浏览器类型", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String browser;

    @Schema(description = "浏览器版本", nullable = true)
    @Column(name = "browser_version", comment = "浏览器版本", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String browserVersion;

    @Schema(description = "平台类型", nullable = true)
    @Column(name = "platform", comment = "平台类型", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String platform;

    @Schema(description = "系统类型", nullable = true)
    @Column(name = "os", comment = "系统类型", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String os;

    @Schema(description = "系统版本", nullable = true)
    @Column(name = "os_version", comment = "系统版本", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String osVersion;

    @Schema(description = "引擎类型", nullable = true)
    @Column(name = "engine", comment = "引擎类型", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String engine;

    @Schema(description = "引擎版本", nullable = true)
    @Column(name = "engine_version", comment = "引擎版本", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String engineVersion;

    @Schema(description = "状态;1-有效，0-无效", nullable = true)
    @Column(name = "status", comment = "状态;1-有效，0-无效", length = 5L, defaultValue = "1", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer status;

    @Schema(description = "备注说明", nullable = true)
    @Column(name = "remarks", comment = "备注说明", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String remarks;

    /**
     * default constructor
     */
    public UmsAdminLoginHistoryDO() {
    }

    /**
     * pk constructor
     */
    public UmsAdminLoginHistoryDO(String id) {
        this.id = id;
    }
    /*---end-auto-generate-don't-update-this-area--*/
}
