/**
 * @Generated by sagacity-quickvo 5.0
 */
package cn.fanzy.atfield.infra.entity;

import cn.fanzy.atfield.sqltoy.entity.BaseEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.BusinessId;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serial;
import java.io.Serializable;
import java.sql.Types;

/**
 * @author fanzaiyang
 * @version 1.0.0
 * @project spider-starter
 */
@EqualsAndHashCode(callSuper = true)
@Schema(description = "组织结构表")
@Data
@Accessors(chain = true)
@Entity(tableName = "ums_org_info", comment = "组织结构表", pk_constraint = "PRIMARY")
public class UmsOrgInfoDO extends BaseEntity implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 7839939799929022156L;
    /*---begin-auto-generate-don't-update-this-area--*/

    @Schema(description = "主键", nullable = false)
    @Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
    @Column(name = "id", comment = "主键", length = 36L, type = Types.VARCHAR, nativeType = "VARCHAR", nullable = false)
    private String id;

    @BusinessId(generator = "redis")
    @Schema(description = "部门编码", nullable = true)
    @Column(name = "code", comment = "部门编码", length = 36L, type = Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String code;

    @Schema(description = "部门名称", nullable = true)
    @Column(name = "name", comment = "部门名称", length = 90L, type = Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String name;

    @Schema(description = "部门负责人ID", nullable = true)
    @Column(name = "master_id", comment = "部门负责人ID", length = 36L, type = Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String masterId;

    @Schema(description = "是否叶子结点;1-是，0-否", nullable = true)
    @Column(name = "is_leaf", comment = "是否叶子结点;1-是，0-否", length = 5L, type = Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer isLeaf;

    @Schema(description = "上级ID", nullable = true)
    @Column(name = "parent_id", comment = "上级ID", length = 36L, type = Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String parentId;
    @Schema(description = "序号", nullable = true)
    @Column(name = "order_number", comment = "上级ID", length = 36L, type = Types.INTEGER, nativeType = "VARCHAR", nullable = true)
    private Integer orderNumber;


    @Schema(description = "节点类型;menu-菜单，button-按钮，api-接口", nullable = true)
    @Column(name = "node_type", comment = "节点类型;menu-菜单，button-按钮，api-接口", length = 36L, type = Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String nodeType;

    @Schema(description = "节点级别", nullable = true)
    @Column(name = "node_level", comment = "节点级别", length = 10L, type = Types.INTEGER, nativeType = "INT", nullable = true)
    private Integer nodeLevel;

    @Schema(description = "节点路由", nullable = true)
    @Column(name = "node_route", comment = "节点路由", length = 65535L, type = Types.VARCHAR, nativeType = "TEXT", nullable = true)
    private String nodeRoute;

    @Schema(description = "节点路由", nullable = true)
    @Column(name = "node_route_name", comment = "节点路由", length = 65535L, type = Types.VARCHAR, nativeType = "TEXT", nullable = true)
    private String nodeRouteName;

    @Schema(description = "备注说明", nullable = true)
    @Column(name = "remarks", comment = "备注说明", length = 900L, type = Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String remarks;

    @Schema(description = "状态;1-有效，0-无效", nullable = true)
    @Column(name = "status", comment = "状态;1-有效，0-无效", length = 5L, defaultValue = "1", type = Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer status;

    /**
     * default constructor
     */
    public UmsOrgInfoDO() {
    }

    /**
     * pk constructor
     */
    public UmsOrgInfoDO(String id) {
        this.id = id;
    }
    /*---end-auto-generate-don't-update-this-area--*/
}
