/**
 *@Generated by sagacity-quickvo 5.0
 */
package cn.fanzy.atfield.infra.entity;

import cn.fanzy.atfield.sqltoy.entity.BaseEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serial;
import java.io.Serializable;

/**
 * @project spider-starter
 * @author fanzaiyang
 * @version 1.0.0 
 */
@Schema(description = "角色菜单对应表")
@EqualsAndHashCode(callSuper = true)
@Data
@Accessors(chain = true)
@Entity(tableName = "ums_role_menu_relation", comment = "角色菜单对应表", pk_constraint = "PRIMARY")
public class UmsRoleMenuRelationDO extends BaseEntity implements Serializable {

	@Serial
	private static final long serialVersionUID = 6319192904547125882L;
	/*---begin-auto-generate-don't-update-this-area--*/

	@Schema(description = "主键", nullable = false)
	@Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name = "id", comment = "主键", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = false)
	private String id;

	@Schema(description = "角色ID", nullable = true)
	@Column(name = "role_id", comment = "角色ID", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String roleId;

	@Schema(description = "菜单ID", nullable = true)
	@Column(name = "menu_id", comment = "菜单ID", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String menuId;

	@Schema(description = "状态;1-有效，0-无效", nullable = true)
	@Column(name = "status", comment = "状态;1-有效，0-无效", length = 5L, defaultValue = "1", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
	private Integer status;

	@Schema(description = "备注说明", nullable = true)
	@Column(name = "remarks", comment = "备注说明", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String remarks;

	/**
	 * default constructor
	 */
	public UmsRoleMenuRelationDO() {
	}

	/**
	 * pk constructor
	 */
	public UmsRoleMenuRelationDO(String id) {
		this.id = id;
	}
	/*---end-auto-generate-don't-update-this-area--*/
}
