/**
 *@Generated by sagacity-quickvo 5.0
 */
package cn.fanzy.atfield.infra.entity;

import cn.fanzy.atfield.sqltoy.entity.BaseEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serial;
import java.io.Serializable;

/**
 * @project spider-starter
 * @author fanzaiyang
 * @version 1.0.0 
 */
@Schema(description = "角色信息表")
@EqualsAndHashCode(callSuper = true)
@Data
@Accessors(chain = true)
@Entity(tableName = "ums_role_info", comment = "角色信息表", pk_constraint = "PRIMARY")
public class UmsRoleInfoDO extends BaseEntity implements Serializable {

	@Serial
	private static final long serialVersionUID = 3938025080571721077L;
	/*---begin-auto-generate-don't-update-this-area--*/

	@Schema(description = "主键", nullable = false)
	@Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name = "id", comment = "主键", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = false)
	private String id;

	@Schema(description = "编码", nullable = true)
	@Column(name = "code", comment = "编码", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String code;

	@Schema(description = "名称", nullable = true)
	@Column(name = "name", comment = "名称", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String name;

	@Schema(description = "数据范围;all：全部数据权限 custom：自定数据权限 dept：本部门数据权限 dept_all：本部门及以下数据权限", nullable = true)
	@Column(name = "data_scope", comment = "数据范围;all：全部数据权限 custom：自定数据权限 dept：本部门数据权限 dept_all：本部门及以下数据权限", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String dataScope;

	@Schema(description = "是否超管;1-是，0-否", nullable = true)
	@Column(name = "is_super_admin", comment = "是否超管;1-是，0-否", length = 5L, defaultValue = "0", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
	private Integer isSuperAdmin;

	@Schema(description = "排序序号", nullable = true)
	@Column(name = "order_number", comment = "排序序号", length = 10L, defaultValue = "0", type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
	private Integer orderNumber;

	@Schema(description = "上级ID", nullable = true)
	@Column(name = "parent_id", comment = "上级ID", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String parentId;

	@Schema(description = "是否叶子结点;1-是，0-否", nullable = true)
	@Column(name = "is_leaf", comment = "是否叶子结点;1-是，0-否", length = 5L, type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
	private Integer isLeaf;

	@Schema(description = "节点类型", nullable = true)
	@Column(name = "node_type", comment = "节点类型", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String nodeType;

	@Schema(description = "节点级别", nullable = true)
	@Column(name = "node_level", comment = "节点级别", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
	private Integer nodeLevel;

	@Schema(description = "节点路由", nullable = true)
	@Column(name = "node_route", comment = "节点路由", length = 65535L, type = java.sql.Types.VARCHAR, nativeType = "TEXT", nullable = true)
	private String nodeRoute;

	@Schema(description = "备注说明", nullable = true)
	@Column(name = "remarks", comment = "备注说明", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String remarks;

	@Schema(description = "类型;1-后台，2-商城", nullable = true)
	@Column(name = "type", comment = "类型;1-后台，2-商城", length = 5L, defaultValue = "1", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
	private Integer type;

	@Schema(description = "状态;1-有效，0-无效", nullable = true)
	@Column(name = "status", comment = "状态;1-有效，0-无效", length = 5L, defaultValue = "1", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
	private Integer status;

	/**
	 * default constructor
	 */
	public UmsRoleInfoDO() {
	}

	/**
	 * pk constructor
	 */
	public UmsRoleInfoDO(String id) {
		this.id = id;
	}
	/*---end-auto-generate-don't-update-this-area--*/
}
