/**
 * @Generated by sagacity-quickvo 5.0
 */
package cn.fanzy.atfield.infra.entity;

import cn.fanzy.atfield.sqltoy.entity.BaseEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.BusinessId;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serial;
import java.io.Serializable;

/**
 * @author fanzaiyang
 * @version 1.0.0
 * @project spider-starter
 */
@Schema(description = "员工信息表")
@Data
@Accessors(chain = true)
@Entity(tableName = "ums_staff_info", comment = "员工信息表", pk_constraint = "PRIMARY")
public class UmsStaffInfoDO extends BaseEntity implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 2470772747389081247L;
    /*---begin-auto-generate-don't-update-this-area--*/

    @Schema(description = "主键", nullable = false)
    @Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
    @Column(name = "id", comment = "主键", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = false)
    private String id;

    @Schema(description = "唯一ID;来源三方的ID", nullable = true)
    @Column(name = "union_id", comment = "唯一ID;来源三方的ID", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String unionId;

    @Schema(description = "头像", nullable = true)
    @Column(name = "avatar", comment = "头像", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String avatar;

    @BusinessId(generator = "redis")
    @Schema(description = "编码", nullable = true)
    @Column(name = "code", comment = "编码", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String code;

    @Schema(description = "姓名", nullable = true)
    @Column(name = "name", comment = "姓名", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String name;

    @Schema(description = "手机号", nullable = true)
    @Column(name = "phone", comment = "手机号", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String phone;

    @Schema(description = "邮箱", nullable = true)
    @Column(name = "email", comment = "邮箱", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String email;

    @Schema(description = "性别;1-男，2-女，0-未知", nullable = true)
    @Column(name = "sex", comment = "性别;1-男，2-女，0-未知", length = 5L, type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer sex;

    @Schema(description = "生日;yyyy-MM-dd", nullable = true)
    @Column(name = "birthday", comment = "生日;yyyy-MM-dd", length = 10L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String birthday;

    @Schema(description = "入职时间;yyyy-MM-dd", nullable = true)
    @Column(name = "entry_time", comment = "入职时间;yyyy-MM-dd", length = 10L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String entryTime;
    @Schema(description = "离职时间;yyyy-MM-dd", nullable = true)
    @Column(name = "depart_time", comment = "离职时间;yyyy-MM-dd", length = 10L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String departTime;

    @Schema(description = "组织ID", nullable = true)
    @Column(name = "org_id", comment = "组织ID", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String orgId;

    @Schema(description = "职务", nullable = true)
    @Column(name = "job_id", comment = "职务", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String jobId;

    @Schema(description = "上级ID", nullable = true)
    @Column(name = "parent_id", comment = "上级ID", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String parentId;

    @Schema(description = "来源", nullable = true)
    @Column(name = "source_type", comment = "来源", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String sourceType;

    @Schema(description = "是否叶子结点;1-是，0-否", nullable = true)
    @Column(name = "is_leaf", comment = "是否叶子结点;1-是，0-否", length = 5L, type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer isLeaf;

    @Schema(description = "节点类型;menu-菜单，button-按钮，api-接口", nullable = true)
    @Column(name = "node_type", comment = "节点类型;menu-菜单，button-按钮，api-接口", length = 36L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String nodeType;

    @Schema(description = "节点级别", nullable = true)
    @Column(name = "node_level", comment = "节点级别", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
    private Integer nodeLevel;

    @Schema(description = "节点路由", nullable = true)
    @Column(name = "node_route", comment = "节点路由", length = 65535L, type = java.sql.Types.VARCHAR, nativeType = "TEXT", nullable = true)
    private String nodeRoute;

    @Schema(description = "备注说明", nullable = true)
    @Column(name = "remarks", comment = "备注说明", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
    private String remarks;

    @Schema(description = "状态;1-有效，0-无效", nullable = true)
    @Column(name = "status", comment = "状态;1-有效，0-无效", length = 5L, defaultValue = "1", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
    private Integer status;

    /**
     * default constructor
     */
    public UmsStaffInfoDO() {
    }

    /**
     * pk constructor
     */
    public UmsStaffInfoDO(String id) {
        this.id = id;
    }
    /*---end-auto-generate-don't-update-this-area--*/
}
