/**
 *@Generated by sagacity-quickvo 5.0
 */
package cn.fanzy.atfield.infra.entity;

import cn.fanzy.atfield.sqltoy.entity.BaseEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serial;
import java.io.Serializable;

/**
 * @project spider-starter
 * @author fanzaiyang
 * @version 1.0.0 
 */
@Schema(description = "客户端UA信息")
@EqualsAndHashCode(callSuper = true)
@Data
@Accessors(chain = true)
@Entity(tableName = "ums_user_device_info", comment = "客户端UA信息", pk_constraint = "PRIMARY")
public class UmsUserDeviceInfoDO extends BaseEntity implements Serializable {

	@Serial
	private static final long serialVersionUID = 3862644822216514807L;
	/*---begin-auto-generate-don't-update-this-area--*/

	@Schema(description = "主键", nullable = false)
	@Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name = "id", comment = "主键", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = false)
	private String id;

	@Schema(description = "用户ID", nullable = true)
	@Column(name = "user_id", comment = "用户ID", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String userId;

	@Schema(description = "是否为移动平台", nullable = true)
	@Column(name = "mobile", comment = "是否为移动平台", length = 1L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String mobile;

	@Schema(description = "浏览器类型", nullable = true)
	@Column(name = "browser", comment = "浏览器类型", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String browser;

	@Schema(description = "浏览器版本", nullable = true)
	@Column(name = "browser_version", comment = "浏览器版本", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String browserVersion;

	@Schema(description = "平台类型", nullable = true)
	@Column(name = "platform", comment = "平台类型", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String platform;

	@Schema(description = "系统类型", nullable = true)
	@Column(name = "os", comment = "系统类型", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String os;

	@Schema(description = "系统版本", nullable = true)
	@Column(name = "os_version", comment = "系统版本", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String osVersion;

	@Schema(description = "引擎类型", nullable = true)
	@Column(name = "engine", comment = "引擎类型", length = 90L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String engine;

	@Schema(description = "引擎版本", nullable = true)
	@Column(name = "engine_version", comment = "引擎版本", length = 32L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String engineVersion;

	@Schema(description = "屏幕的宽", nullable = true)
	@Column(name = "screen_width", comment = "屏幕的宽", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
	private Integer screenWidth;

	@Schema(description = "屏幕的高", nullable = true)
	@Column(name = "screen_height", comment = "屏幕的高", length = 10L, type = java.sql.Types.INTEGER, nativeType = "INT", nullable = true)
	private Integer screenHeight;

	@Schema(description = "状态;1-有效，0-无效", nullable = true)
	@Column(name = "status", comment = "状态;1-有效，0-无效", length = 5L, defaultValue = "1", type = java.sql.Types.SMALLINT, nativeType = "SMALLINT", nullable = true)
	private Integer status;

	@Schema(description = "备注说明", nullable = true)
	@Column(name = "remarks", comment = "备注说明", length = 900L, type = java.sql.Types.VARCHAR, nativeType = "VARCHAR", nullable = true)
	private String remarks;

	/**
	 * default constructor
	 */
	public UmsUserDeviceInfoDO() {
	}

	/**
	 * pk constructor
	 */
	public UmsUserDeviceInfoDO(String id) {
		this.id = id;
	}
	/*---end-auto-generate-don't-update-this-area--*/
}
