spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    username: hotec
    password: hotec123qwe.?
    url: jdbc:mysql://mysql.wanghuifeng.me:3306/yf_common_test?useUnicode=true&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      validation-query: select 1
      filters: stat,wall,slf4j
      stat-view-servlet:
        url-pattern: /druid/*
        enabled: true
        login-password: admin
        login-username: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: cn.fanzy.breeze.admin.*
  profiles:
    include: db
#breeze:
#  web:
#    code:
#      enable: true
#      delete-on-success: true #是否在验证成功后删除验证过的验证码,默认为true
#      show-log: false #是否显示加载日志，默认为false
#      prefix: validate_code_ #将验证码存储到Redis或内存时的key的前缀，默认值为validate_code_
#      retry-count: 1 #重试计数,默认1，即验证次数超过此参数时，删除验证码，需要使用新码。全局配置，可被子配置覆盖。
#      image:
#        code-key: image #从请求中获取图形验证码的客户端的参数，默认值为 image
#        code-value: code #请求中获取图形验证码对应的值的参数，默认值为 code
#        length: 4 #验证码的长度,默认为4
#        expire-in: 300 #验证码的失效时间，单位秒，默认为300s
#        contain-letter: false #验证码是否包含字母,默认不包含
#        contain-number: true #验证码是否包含数字,默认包含
#        retry-count: 1 #重试计数,默认1，即验证次数超过此参数时，删除验证码，需要使用新码。
#        width: 70 #验证码的宽度,默认为70
#        height: 28 #验证码的高度,默认为 28
#        fringe: false #是否生成干扰条纹背景，默认为false
#      sms:
#        code-key: phone #从请求中获取短信验证码的发送目标(手机号)的参数，默认值为 phone
#        code-value: code #请求中获取短信验证码对应的短信内容的参数，默认值为 phone_code
#        retry-count: 1 #重试计数,默认1，即验证次数超过此参数时，删除验证码，需要使用新码。
#        length: 4 #验证码的长度,默认为4
#        expire-in: 300 #验证码的失效时间，单位秒，默认为300s
#        contain-letter: false #验证码是否包含字母,默认不包含
#        contain-number: true #验证码是否包含数字,默认包含
#      email:
#        code-key: email #从请求中获取短信验证码的发送目标(手机号)的参数，默认值为 phone
#        code-value: code #请求中获取短信验证码对应的短信内容的参数，默认值为 phone_code
#        retry-count: 1 #重试计数,默认1，即验证次数超过此参数时，删除验证码，需要使用新码。
#        length: 4 #验证码的长度,默认为4
#        expire-in: 300 #验证码的失效时间，单位秒，默认为300s
#        contain-letter: false #验证码是否包含字母,默认不包含
#        contain-number: true #验证码是否包含数字,默认包含
#        sender-address: xxxx@xx.com #发送验证码的邮箱，必填
#        title: 帐号保护验证 #验证码邮箱的标题
#breeze:
#  minio:
#    servers:
#      # 第一个minio服务配置
#      test:
#        access-key: minioadmin #账号，必填项。
#        secret-key: minioadmin #密码，必填项。
#        bucket: test #默认的存储桶，必填项。
#        endpoint: http://minio.zaiyang.top # minio服务地址，必填项
#        inner-endpoint: http://minio.zaiyang.top # minio内网服务地址，目的加速文件上传，非必填项，默认同endpoint。
#      # 第二个minio服务配置
#      prod:
#        access-key: minioadmin #账号，必填项。
#        secret-key: minioadmin #密码，必填项。
#        bucket: test2 #默认的存储桶，必填项。
#        endpoint: http://minio.zaiyang.top # minio服务地址，必填项
#        inner-endpoint: http://minio.zaiyang.top # minio内网服务地址，目的加速文件上传，非必填项，默认同endpoint。
#breeze:
#  wechat:
#    # 企业微信相关配置
#    cp:
#      corp-id: 1234 #设置企业微信的corpId，必填项。
#      app-configs:
#        # 第一个应用
#        - agent-id: 1001 #应用ID，必填项。
#          secret: abc #应用密钥，必填项。
#          token: token #设置企业微信应用的token,非必填。
#          aes-key: ase-key #设置企业微信应用的EncodingAESKey,非必填。
#        # 第而个应用
#        - agent-id: 1002 #应用ID，必填项。
#          secret: abc #应用密钥，必填项。
#          token: token #设置企业微信应用的token,非必填。
#          aes-key: ase-key #设置企业微信应用的EncodingAESKey,非必填。
#    ma:
#      app-configs:
#        - app-id: app_id #设置微信小程序的appid.必填项。
#          secret: secret #设置微信小程序的Secret.必填项。
#          token: token #非必填。
#          aes-key: aes-key #非必填。
#          msg-data-format: JSON #消息格式，XML或者JSON.非必填。
#    mp:
#      app-configs:
#        - app-id: app_id #设置微信公众号的appid.必填项。
#          secret: secret #设置微信公众号的Secret.必填项。
#          token: token #非必填。
#          aes-key: aes-key #非必填。
#    pay:
#      app-id: app_id #设置微信支付的appid
#      mch-id: mch_id #微信支付商户号
#      mch-key: mch-key #微信支付商户密钥
#      sub-app-id: sub_app_id #服务商模式下的子商户公众账号ID，普通模式请不要配置，请在配置文件中将对应项删除
#      sub-mch-id: sub_mch_id #服务商模式下的子商户号，普通模式请不要配置，最好是请在配置文件中将对应项删除
#      key-path: key_path #apiclient_cert.p12文件的绝对路径，或者如果放在项目中，请以classpath:开头指定
#      use-sandbox-env: false #以指定是否使用沙箱环境,默认false
breeze:
  auth:
    route:
      exclude-path-patterns: /auth/**,/test/**
  web:
    safe:
      need-code: true
  admin:
    error-level: error # 记录日志到数据库的级别，error：只写入错误日志，all：写入所有到数据库(默认)
    default-password: 123456a? #默认的登录密码,默认：123456a?
    module: # 模块配置
      enable-account: true # 启用系统管理/账户管理模块，默认：true
      enable-auth: true # 启用授权登录模块，默认：true
      enable-dict: true # 启用系统管理/字典管理模块，默认：true
      enable-menu: true # 启用系统管理/菜单管理模块，默认：true
      enable-org: true # 启用系统管理/组织管理模块，默认：true
      enable-role: true # 启用系统管理/角色管理模块，默认：true
      enable-system: true # 启用系统管理模块，默认：true
    prefix:
      api: / # 全局接口前缀，适用于本组件的前缀。
      account: /sys/account # 系统管理/账户管理模块的接口，默认：/sys/account
      auth: /auth # 授权登录模块的接口，默认：/auth
      dict: /sys/dict # 系统管理/字典管理模块，默认：/sys/dict
      menu: /sys/menu # 系统管理/菜单管理模块，默认：/sys/menu
      org: /sys/org # 系统管理/组织管理模块，默认：/sys/org
      role: /sys/role # 系统管理/角色管理模块，默认：/sys/role
    app-name: 微风组件
  minio:
    servers:
      -test:
        endpoint: http://minio.zaiyang.top
        access-key: minioadmin
        secret-key: minioadmin
        bucket: test
knife4j:
  enable: true
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.fanzy.breeze.demo
  api-docs:
    groups:
      enabled: false

