infra:
  log:
    enable-invoke-time-print: true
  web:
    response:
      wrapper:
        enable: true
    json:
      model:
        enable-error-stack: true
      convert:
        enable: false
  captcha:
    image:
      retry-count: 3