spring:
  datasource:
    url: jdbc:mysql://mysql.wanghuifeng.me:3306/yf_common_test?useUnicode=true&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hotec
    password: hotec123qwe.?
  sqltoy:
    sql-resources-dir: classpath:sql #指定sql.xml 文件路径,多个路径用逗号分隔。示例表示在resours下的sql文件夹下。
    debug: true
breeze:
  web:
    code:
      enable: true
      delete-on-success: true #是否在验证成功后删除验证过的验证码,默认为true
      show-log: false #是否显示加载日志，默认为false
      prefix: validate_code_ #将验证码存储到Redis或内存时的key的前缀，默认值为validate_code_
      retry-count: 1 #重试计数,默认1，即验证次数超过此参数时，删除验证码，需要使用新码。全局配置，可被子配置覆盖。
      image:
        code-key: image #从请求中获取图形验证码的客户端的参数，默认值为 image
        code-value: code #请求中获取图形验证码对应的值的参数，默认值为 code
        length: 4 #验证码的长度,默认为4
        expire-in: 300 #验证码的失效时间，单位秒，默认为300s
        contain-letter: false #验证码是否包含字母,默认不包含
        contain-number: true #验证码是否包含数字,默认包含
        retry-count: 1 #重试计数,默认1，即验证次数超过此参数时，删除验证码，需要使用新码。
        width: 70 #验证码的宽度,默认为70
        height: 28 #验证码的高度,默认为 28
        fringe: false #是否生成干扰条纹背景，默认为false
      sms:
        code-key: phone #从请求中获取短信验证码的发送目标(手机号)的参数，默认值为 phone
        code-value: code #请求中获取短信验证码对应的短信内容的参数，默认值为 phone_code
        retry-count: 1 #重试计数,默认1，即验证次数超过此参数时，删除验证码，需要使用新码。
        length: 4 #验证码的长度,默认为4
        expire-in: 300 #验证码的失效时间，单位秒，默认为300s
        contain-letter: false #验证码是否包含字母,默认不包含
        contain-number: true #验证码是否包含数字,默认包含
      email:
        code-key: email #从请求中获取短信验证码的发送目标(手机号)的参数，默认值为 phone
        code-value: code #请求中获取短信验证码对应的短信内容的参数，默认值为 phone_code
        retry-count: 1 #重试计数,默认1，即验证次数超过此参数时，删除验证码，需要使用新码。
        length: 4 #验证码的长度,默认为4
        expire-in: 300 #验证码的失效时间，单位秒，默认为300s
        contain-letter: false #验证码是否包含字母,默认不包含
        contain-number: true #验证码是否包含数字,默认包含
        sender-address: xxxx@xx.com #发送验证码的邮箱，必填
        title: 帐号保护验证 #验证码邮箱的标题
        content-template: 您的验证码的内容为{0} ,验证码的有效时间为 {1} 秒 #验证码邮箱的内容模板
