spring:
  datasource:
    url: jdbc:mysql://mysql.wanghuifeng.me:3306/yf_common_test?useUnicode=true&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hotec
    password: hotec123qwe.?
  sqltoy:
    sql-resources-dir: classpath:sql #指定sql.xml 文件路径,多个路径用逗号分隔。示例表示在resours下的sql文件夹下。
    debug: true
breeze:
  web:
    code:
      enable: true
    ip:
      enable: true
      allowed: 172.0.0.1,192.168.0.1
      deny: 192.168.13.1,192.168.13.2
      path-patterns: /auth/**,/user/**
#    unify-fields-handler: com.example.breeze.web.sql.BreezeUnifyFieldsHandler