# 数据库 及 Redis 配置
spring:
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  datasource:
    url: jdbc:mysql://mysql.wanghuifeng.me:3306/yf_common_test?useUnicode=true&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hotec
    password: hotec123qwe.?
    hikari:
      connection-timeout: 30000
      idle-timeout: 25000
      max-lifetime: 30000
      validation-timeout: 3000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      maximum-pool-size: 4
      minimum-idle: 2
  aop:
    auto: true
    proxy-target-class: true
  #配置jackson返回日期的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-prefix: null
    optimistic-locker: false
  configuration:
    cache-enabled: false
    default-executor-type: reuse
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: true
    local-cache-scope: session
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler   # EnumTypeHandler 配置为它时不能识别默认GenderEnum

breeze:
  minio:
    servers:
      test:
        endpoint: http://minio.zaiyang.top
        access-key: minioadmin
        secret-key: minioadmin
        bucket: test